version: '3.3'
services:
  mysqlMaster:
    image: mysql/mysql-server:8.0.15
    container_name: mysqlMaster
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=db_cooking_with_java
      - MYSQL_USER=cookingWithJavaUser
      - MYSQL_PASSWORD=cookingWithJavaPass
  MainApp1:
    build: ./MainApp
    image: cookingwithjava-mainapp
    container_name: MainApp1
    depends_on:
      - "mysqlMaster"
      - "InternalServiceProxy"
    environment:
      - SPRING_DATASOURCE_USERNAME=cookingWithJavaUser
      - SPRING_DATASOURCE_PASSWORD=cookingWithJavaPass
      - WAIT_HOSTS=mysqlMaster:3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlMaster:3306/db_cooking_with_java?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SERVER_PORT=9001
      - HAZELCAST_URL1=MainApp1
      - HAZELCAST_URL2=MainApp2
      - URL_APP_PRINCIPAL=https://127.0.0.1:8443
      - INTERNAL_SERVICE_URL=http://InternalServiceProxy:7000
  MainApp2:
    build: ./MainApp
    image: cookingwithjava-mainapp
    container_name: MainApp2
    depends_on:
      - "mysqlMaster"
      - "InternalServiceProxy"
    environment:
      - SPRING_DATASOURCE_USERNAME=cookingWithJavaUser
      - SPRING_DATASOURCE_PASSWORD=cookingWithJavaPass
      - WAIT_HOSTS=mysqlMaster:3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlMaster:3306/db_cooking_with_java?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SERVER_PORT=9002
      - HAZELCAST_URL1=MainApp1
      - HAZELCAST_URL2=MainApp2
      - URL_APP_PRINCIPAL=https://127.0.0.1:8443
      - INTERNAL_SERVICE_URL=http://InternalServiceProxy:7000
  MainProxy:
    build: ./MainProxy
    image: cookingwithjava-mainproxy
    container_name: MainProxy
    depends_on:
      - "MainApp1"
      - "MainApp2"
    ports:
     - "8443:8443"
     - "1936:1936"
     - "8080:8080"
  InternalService1:
    build: ./InternalService
    image: cookingwithjava-internalservice
    container_name: InternalService1
    environment:
      - SERVER_PORT=7001
  InternalService2:
    build: ./InternalService
    image: cookingwithjava-internalservice
    container_name: InternalService2
    environment:
      - SERVER_PORT=7002
  InternalServiceProxy:
    build: ./InternalServiceProxy
    image: cookingwithjava-internalproxy
    container_name: InternalServiceProxy
    depends_on:
      - "InternalService1"
      - "InternalService2"
    expose:
      - "7000"
    ports:
     - "1937:1937"